import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import HeroDay from "../../public/Devpoint-Day-Anime.png";
import HeroNight from "../../public/Devpoint-Night-Anime1.png";
import Profile from "../../public/Devpoint-DigitalArt.png";
import AnimatedText from "@/components/AnimatedText";
import { ExternalLinkIcon } from "@/components/Icons";
import Link from "next/link";
import HireMe from "@/components/HireMe";
import { motion } from "framer-motion";

const FramerImage = motion(Image);

export default function Home() {
  return (
    <>
      <Head>
        <title>DevPoint | Main</title>
        <meta name="description" content="Generated by Create Next App" />
      </Head>
      <div className="flex items-center text-dark w-full pb-16 dark:text-light">
        <Layout className="sm:px-12 sm:pt-8 md:pt-16">
          <div className="flex items-center justify-between w-full gap-10 md:flex-col">
            <div className="w-1/2 flex justify-center items-end md:w-full lg:w-0">
              <FramerImage
                src={HeroDay}
                alt="DevPoint"
                initial={{ opacity: 0, y: 30 }}
                whileInView={{
                  opacity: 1,
                  y: 0,
                  transition: { duration: 0.4 },
                }}
                className="w-full h-auto lg:hidden md:inline-block 3xl:max-w-[400px] rounded-3xl dark:hidden"
                priority
                sizes="
                  (max-width: 768px) 100vw,
                  (max-width: 1200px) 50vw,
                  33vw
                "
              />
              <FramerImage
                src={HeroNight}
                alt="DevPoint"
                initial={{ opacity: 0, y: 30 }}
                whileInView={{
                  opacity: 1,
                  y: 0,
                  transition: { duration: 0.4 },
                }}
                className="w-full h-auto lg:hidden 3xl:max-w-[350px] max-h- rounded-3xl hidden dark:inline-block dark:lg:hidden"
                priority
                sizes="
                  (max-width: 768px) 100vw,
                  (max-width: 1200px) 50vw,
                  33vw
                "
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:mb-12">
              <AnimatedText
                text="Turning Vision Into Reality With Code And Innovation."
                className="select-none lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl 3xl:!text-6xl 3xl:!text-left xl:!text-5xl"
              />
              <p className="my-4 text-base font-medium select-none md:text-sm">
                As a skilled Full-Stack Developer, I am dedicated to turning
                Innovative Ideas into Reality Web Applications. Explore my
                latest projects and articles, showcasting my expertise in
                React.JS, React Native and Kotlin Web and Mobile Development.
              </p>
              <div className="grid sm:grid-cols-1 2xl:grid-cols-2 3xl:grid-cols-3 items-center self-start mt-2 gap-5">
                <Link
                  href="/VictorTejadaResume.pdf"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark transition-all duration-200 min-w-[200px] justify-center w-fit dark:bg-light dark:text-dark dark:hover:bg-dark dark:hover:text-white dark:hover:border-light sm:px-3 sm:min-w-[100px]"
                  download={true}
                >
                  Resume Eng &nbsp; <ExternalLinkIcon className="sm:hidden" />{" "}
                </Link>
                <Link
                  href="/VictorTejadaCV.pdf"
                  target={"_blank"}
                  className="flex items-center text-center bg-blue-600 text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-blue-600 border-2 border-solid border-transparent hover:border-blue-600 transition-all duration-200 justify-center w-fit dark:hover:bg-dark sm:ml-0 sm:px-3 3xl:ml-4"
                  download={true}
                >
                  CV Esp &nbsp; <ExternalLinkIcon />
                </Link>
                <Link
                  href="mailto:misterypoint2@gmail.com"
                  target={"_blank"}
                  className="text-lg font-medium capitalize text-dark underline dark:text-light"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className="fixed right-0 bottom-12 inline-block 3xl:max-w-[250px] 2xl:max-w-[200px] xl:max-w-[150px] lg:max-w-[125px] lg:bottom-16 md:hidden">
          <Image
            src={Profile}
            alt={"DevPoint Digital Art"}
            className="w-full h-auto"
          />
        </div>
      </div>
    </>
  );
}
